config/routes.rb
Rails.application.routes.draw do


  # Index/Welcome Routes
	root to: "welcome#index"

  # Sessions Routes
	get "/log_in", to: "sessions#new", as: "log_in"
	post "/sessions", to: "sessions#create"
	delete "/sessions", to: "sessions#destroy", as: "logout"

  # User Routes
	resources :users

  #Post Routes
  resources :posts

  #City Routes
  get 'cities', to: "cities#index", as: "cities"
  get 'cities/:id', to: "cities#show", as: "city"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :posts, dependent: :destroy 
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :city
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :posts, dependent: :destroy 

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  	@cities = City.all
  end

  def show
  	@city = City.find(params[:id])
  	@keywords = @city.keywords
  	@posts = @city.posts.order(:created_at => :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
     @posts = Post.find(params[:id])
  end

  # POST /posts
  def create
    city_id = post_params[:city_id]
    @city = City.find_by_id(city_id)
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.date_created = Time.now.strftime("%Y-%d-%m %H:%M:%S %Z")
    @post.city_id = city_id
    @post.save
    redirect_to city_path(@city)
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to user_path(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :summary, :city_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		# @user = User.new
		# render :new
	end

	def create
		user_params = params.require(:user).permit(:email, :password)
		@user = User.confirm(user_params)
		if @user
		  login(@user)
		  redirect_to "/users/#{@user.id}"
		else
		  redirect_to root_path
		end
	end

	def destroy
		current_user
		logout
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:index, :show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @date = @user.created_at.strftime("%b %d, %Y")
  end

  # GET /users/new
  def new
    # @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.create(user_params)
    login(@user)
    redirect_to user_path(@user)
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to user_path(@user)
  end

  # DELETE /users/1
  def destroy
    user = User.find(params[:id])
    user.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      user_params = params.require(:user).permit(:first_name, :last_name, :current_city, :profile_photo, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@cities = City.all 
  
  end

  def test
  	render "show.temp.html.erb"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
  	user = session[:user_id]
  	if user != nil
  		@current_user ||= User.find(session[:user_id])
  	end
  end

  def logged_in?
    if current_user == nil
      redirect_to "/log_in"
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/show.html.erb
<!-- New Post Modal -->
<div id="postModal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">New Post</h4>
			</div>
			<div class="modal-body">
				<%= form_for(Post.new) do |f| %>
					<div class="form-group">
						<label for="title">Title:</label>
						<%= f.text_field :title, placeholder: "Post Title", :class => 'form-control' %>
					</div>
					<div class="form-group">
						<label for="last_name">Last Name:</label>
						<%= f.text_area :summary, placeholder: "Post Summary", :class => 'form-control' %>
					</div>
					<div class= "form-group">
						<%= f.hidden_field :city_id, :value => @city.id %>
					</div>
					<%= f.submit "Submit", :class => 'btn btn-default' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<div style="background: url(<%=@city.photo_url%>) no-repeat center center scroll" class="hero-city">
</div>
<div id="start_change" class="city-content col-md-10 col-md-offset-1">
	<h1 class="city-headline">
	  <strong><%= @city.name %></strong>
	</h2>
	<h2>
		<% @keywords.each do |keyword| %> 
			| <%= keyword %> |
		<% end %>
	</h2>
	<h3 class="summary">
		<strong>Summary:</strong>
		<p><%= @city.description %></p>
	</h3>
	<button class="btn btn-primary"><a href="#postModal" role="button" data-toggle="modal" id="new-post">New Post</a></button>
</div>

<div class="col-md-10 col-md-offset-1 profile-body">
	<% @posts.each do |post| %> 
		<p class="post-headline"><%= User.find_by_id(post.user_id)[:first_name] %>  wrote...</p>
		<div class="col-md-12 post-box">
			<p class="post-title"><span style="font-weight: 500">"<%=post.title %>"</span> on <%= post.date_created %></p>
			<p class="post-summary"><%= post.summary %></p>
		</div>
		<div class="col-md-12 post-buttons">
			<%= link_to 'Edit', edit_post_path(post) %> | 
			<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %> |
			<%= link_to 'Show', post %>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagabond</title>
    <%= csrf_meta_tags %>
    <!--jquery-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-rc1/jquery.min.js"></script>

    <!-- Lato Font -->
    <link href='https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!--boostrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <header>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-fixed-top" id="navbar-def">
        <div class="container-fluid">
            <div class="navbar-header">
                <!--Burger navbar -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Vagabond</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <% if current_user == nil %>
                  <li>
                    <a href="#loginModal" role="button" data-toggle="modal">Login</a>
                  </li>
                  <li>
                    <a href="#registerModal" role="button" data-toggle="modal">Register</a>
                  </li>
                <% else %>
                  <li>
                    <a href="/users/<%=current_user.id%>">My Account</a>
                  </li>
                  <li>
                    <%= link_to 'Logout', logout_path, method: :delete %>
                  </li>
                <% end %>
              </ul>
            </div>
        </div>
    </nav>

    <!-- Register Modal -->
    <div id="registerModal" class="modal fade" role="dialog">
       <div class="modal-dialog">
           <!-- Modal content-->
           <div class="modal-content">
               <div class="modal-header">
                   <button type="button" class="close" data-dismiss="modal">&times;</button>
                   <h4 class="modal-title">Register</h4>
               </div>
               <div class="modal-body">
                   <%= form_for(User.new) do |f| %>
                   <div class="form-group">
                     <label for="first_name">First Name:</label>
                     <%= f.text_field :first_name, placeholder: "First Name", :class => 'form-control' %>
                   </div>
                   <div class="form-group">
                     <label for="last_name">Last Name:</label>
                     <%= f.text_field :last_name, placeholder: "Last Name", :class => 'form-control' %>
                   </div>
                   <div class="form-group">
                     <label for="email">Email:</label>
                     <%= f.text_field :email, placeholder: "Email", :class => 'form-control' %>
                   </div>
                   <div class="form-group">
                     <label for="password_digest">Password:</label>
                     <%= f.password_field :password, placeholder: "Password", :class => 'form-control' %>
                   </div>
                   <div class="form-group">
                     <label for="current_city">Current City:</label>
                     <%= f.text_field :current_city, placeholder: "Current City", :class => 'form-control' %>
                   </div>
                   <div class="form-group">
                     <label for="profile_photo">Profile Photo:</label>
                     <%= f.text_field :profile_photo, placeholder: "Link to Photo", :class => 'form-control' %>
                   </div>
                    <%= f.submit "Submit", :class => 'btn btn-default' %>
                 <% end %>
               </div>
           </div>
       </div>
    </div>

    <!-- Login Modal -->
    <div id="loginModal" class="modal fade" role="dialog">
       <div class="modal-dialog">
           <!-- Modal content-->
           <div class="modal-content">
               <div class="modal-header">
                   <button type="button" class="close" data-dismiss="modal">&times;</button>
                   <h4 class="modal-title">Login</h4>
               </div>
               <div class="modal-body">
                 <%= form_for User.new, url: "/sessions", method: "post" do |f| %>
                   <div class="form-group">
                     <label for="email">Email:</label>
                     <%= f.text_field :email, placeholder: "Email", :class => "form-control" %>
                   </div>
                   <div class="form-group">
                     <label for="password_digest">Password:</label>
                     <%= f.password_field :password, placeholder: "Password", :class => "form-control" %>
                   </div>
                   <%= f.submit "Sign In", :class => "btn btn-default" %>
                   <% end %>
               </div>
           </div>
       </div>
    </div>
    </header>

  <%= yield %>

  </body>
</html>

app/views/locations/show.temp.html.erb
<div class="hero" style="background">
    <p>Denver</p>
</div>
<div class="places_container">
    <div class="row">
        <p class="post-headline"><%= @user.first_name %>
            wrote...</p>
        <div class="col-md-12 post-box">
            <p class="post-title">
                <span style="font-weight: 500">"<%= post.title %>"</span>
                on
                <%= post.date_created %></p>
            <p class="post-summary"><%= post.summary %></p>
        </div>
        <div class="col-md-12 post-buttons">
            <%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <div class="form-group">
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.text_area :summary %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="edit-post-page">
	<div id="edit-form" class="col-md-6 col-md-offset-3 profile-box">
		<br>
		<h1>Editing Your Post</h1>
		<br>
		<%= render 'form', post: @post %>
		<br>
	</div>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.summary %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="profile-page">
	<div class="col-md-6 col-md-offset-3 profile-box">
		<div class="col-md-10 col-md-offset-1 profile-body">
			<p class="post-headline"><%= User.find_by_id(@post.user_id)[:first_name] %>  wrote...</p>
			<div class="col-md-12 post-box">
				<p class="post-title"><span style="font-weight: 500">"<%=@post.title %>"</span> on <%= @post.date_created %></p>
				<p class="post-summary"><%= @post.summary %></p>
			</div>
			<div class="col-md-12 post-buttons">
				<%= link_to 'Edit', edit_post_path(@post) %> | 
				<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
		</div>
	</div>
</div>

app/views/users/_edit_form.html.erb
<%= form_for(@user) do |f| %>
    <div>
      <%= f.text_field :first_name, placeholder: "First Name" %>
    </div>
    <div>
      <%= f.text_field :last_name, placeholder: "Last Name" %>
    </div>
    <div>
      <%= f.text_field :email, placeholder: "Email" %>
    </div>
    <div>
      <%= f.password_field :password, placeholder: "Password" %>
    </div>
    <div>
      <%= f.text_field :current_city, placeholder: "Current City" %>
    </div>
    <div>
      <%= f.text_field :profile_photo, placeholder: "Link to Photo" %>
    </div>
    <%= f.submit "Submit" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(User.new) do |f| %>
    <div>
      <%= f.text_field :first_name, placeholder: "First Name" %>
    </div>
    <div>
      <%= f.text_field :last_name, placeholder: "Last Name" %>
    </div>
    <div>
      <%= f.text_field :email, placeholder: "Email" %>
    </div>
    <div>
      <%= f.password_field :password, placeholder: "Password" %>
    </div>
    <div>
      <%= f.text_field :current_city, placeholder: "Current City" %>
    </div>
    <div>
      <%= f.text_field :profile_photo, placeholder: "Link to Photo" %>
    </div>
    <%= f.submit "Submit" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'edit_form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="profile-page">
	<div class="col-md-6 col-md-offset-3 profile-box">
		<div class="col-md-12 profile-head">
			<div id="start_change" class="profile-img start_change" style="background-image: url('<%= @user.profile_photo %>')">
			</div>
			<p class="user-name"><%= @user.first_name %> <%= @user.last_name %></p>
			<p class="profile-details">Email: <%= @user.email %>  |  City: <%= @user.current_city %>  |  Member Since: <%= @date %></p>
		</div>
		<div class="col-md-10 col-md-offset-1 profile-body">
			<% @user.posts.each do |post| %> 
				<p class="post-headline"><%= @user.first_name %> wrote...</p>
				<div class="col-md-12 post-box">
					<p class="post-title"><span style="font-weight: 500">"<%= post.title %>"</span> on <%= post.date_created %></p>
					<p class="post-summary"><%= post.summary %></p>
				</div>
				<div class="col-md-12 post-buttons">
					<%= link_to 'Edit', edit_post_path(post) %> | 
        			<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="hero" style="background: url('http://www.tourscampania.com/wp-content/uploads/2015/12/naples_02.jpg') no-repeat center center; background-size: cover;">
    <p id="start_change">Roam free.   Join our community.</p>
</div>

<div class="places_container">
    <div class="row">
        <% @cities.each do |city| %>
            <div class="col-xs-10 col-xs-offset-1 place">
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <img class="mini-location-pic" src="<%=city.photo_url%>" />
                    </div>
                    <div class="col-xs-12 col-md-6 city-sidebar">
                        <a href="/cities/<%=city.id%>"><p class="city-name"><%=city.name%></p></a>
                        <% city.keywords.each do |keyword| %>
                            <p class="keywords">| <%= keyword %> |</p>
                        <% end %>
                    </div>       
                </div>         
            </div>
        <% end %>
    </div>
</div>